server:
  port: 8084
spring:
  cloud:
    stream:
      function:
        definition: userCreatedConsumer
        bindings:
          userCreatedConsumer-in-0: 'user-created-consumer'
      bindings:
        userCreatedConsumer-in-0:
          destination: 'user-topic'
          consumer:
            concurrency: 1
            max-attempts: 5
      kafka:
        binder:
          brokers: 'localhost:9092'